### ISSUE TITLE
issue with : semicolons in typescript files 

### ISSUE THREAD

**Issue by aldoso** [atom/one-light-ui#110] opened 2017-10-28 08:14 UTC
Hi, there is an issue with this theme: for .ts files : becomes a black rectangle for some reason :( In other file types this issue doesn't reproduce, fortunately

![image](https://user-images.githubusercontent.com/30396343/32132670-9ddbe1a2-bbd0-11e7-8cac-0d0b8e6fe7a2.png)

**Comment by rsese** [comment] 2017-10-30 20:17
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/one-light-syntax/issues/38. You may want to subscribe there for updates.  Also, see this CSS workaround that seems to work ok for me /cc https://github.com/atom/one-light-syntax/issues/38#issuecomment-337266083.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-30 20:17 UTC
