### ISSUE TITLE
Cannot click on the file in tree view right above ":selected list-item" when enable "Make tree view header sticky", 

### ISSUE THREAD

**Issue by Liby99** [atom/one-light-ui#136] opened 2018-05-31 17:57 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For recent days I'm not able to click on the file in tree view above the selected one. The simple walk-around was to click on any other file and then click back to the one I want to open. After opening the inspect element I found that there's an extra style added to the "selected list-item":

``` css
[theme-one-light-ui-sticky-headers="sticky"] .tree-view .list-item.selected {
    padding-top: 2.5em;
    margin-top: -2.5em;
}
```

This is going to make the selected item shift upward 2.5em and has a padding-top 2.5em, and hence the list-item above it is not clickable. I could either disable these styles in inspect element or disable the "Make tree view header sticky" in one-light-ui setting to make the `list-item` above the `:selected` one clickable. But I think this is definitely a bug to be fixed.

### Steps to Reproduce

1. Enable the "Make tree view header sticky" in the one-light-ui setting.
2. Click on files across different folders multiple times.
3. Click on any file (that is not the first one in the directory) in the tree view except the header and directories.
4. Try to click on the file above the selected one.

**Expected behavior:** Click on the file above the selected one will also open that file

**Actual behavior:** The list-item above the selected one is non-clickable so the user is not able to open that file

**Reproduces how often:** 70%

### Versions

$ atom --version
Atom: 1.27.2
Electron: 1.7.15
Chrome: 58.0.3029.110
Node: 7.9.0

$ apm --version
APM: 1.19.0
NPM: 3.10.10
Node: 6.9.5 x64

### Additional Information

None

**Comment by rsese** [comment] 2018-05-31 20:37
Thanks for contributing!

This is a duplicate of https://github.com/atom/one-dark-ui/issues/257 which is [fixed](https://github.com/atom/one-light-ui/pull/133) as of 1.28 (currently in beta).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

https://github.com/atom/one-light-ui/pull/133

**Closed by rsese** 2018-05-31 20:37 UTC
