### ISSUE TITLE
White text on white background in Command Pallete

### ISSUE THREAD

**Issue by iharsuvorau** [atom/one-light-ui#26] opened 2015-05-26 12:05 UTC
Command Pallete `Shift + Cmd + P` shows keyboard shortcuts with white text on white. 
UI Theme: One Light. 
Syntax Theme: One Light.

**Comment by mnquintana** [comment] 2015-05-26 12:08
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/6923 and has been fixed for the next version of Atom (0.202.0).

**Comment by nicolasmccurdy** [comment] 2015-05-26 14:42
I can confirm this with One Light in safe mode.

**Closed** 2015-05-26 16:39 UTC
