### ISSUE TITLE
In One Light/Dark UI Theme Tab Icon and File Name are Overlapping

### ISSUE THREAD

**Issue by fatihturan** [atom/one-light-ui#102] opened 2017-06-07 14:12 UTC
Hi,

In One Light/Dark UI theme tab icons and file names are overlaping in tab. How do I fix this issue?

Also could this be related to the "file icons" package? I have added and removed this package before?

Plus, I've runned the Atom with safe mode. At the result there are no icons on tabs: https://cl.ly/koEp

How it could be? I've uninstalled the File Icons package already.

[Atom 1.17.2 + One Light UI 1.10.3]

**Comment by simurai** [comment] 2017-06-08 08:20
> tab icons and file names are overlaping in tab.

Could you post a screenshot? With `file-icons` installed, it should look like this:

![image](https://user-images.githubusercontent.com/378023/26918823-7ccb1324-4c6e-11e7-910c-afff43b2315b.png)

**Comment by fatihturan** [comment] 2017-06-08 08:38
It's working well with File Icons package. Screenshot: https://cl.ly/kosQ

**Comment by simurai** [comment] 2017-06-08 08:45
Hmm.. I don't see any overlapping in that screenshot? Do you mean the problem is fixed?

**Comment by fatihturan** [comment] 2017-06-08 08:57
But I don't want to use File Icons package. If I uninstall the File Icons package, tab text and tab icons become overlapping (which I mentioned first comment of this issue).

**Comment by simurai** [comment] 2017-06-09 01:06
Sorry, I understand now:

- With `file-icons` it looks ok
- With `safe mode` it looks ok, it has no icons

This can only mean that another package adds icons that look overlapped. Do you have any other packages installed that might add icons?

If you run the `apm list` command, it should show a list of all your Atom packages.

**Comment by fatihturan** [comment] 2017-06-09 08:13
> Sorry, I understand now:

> With file-icons it looks ok
> With safe mode it looks ok, it has no icons

Exactly.

> This can only mean that another package adds icons that look overlapped. Do you have any other packages installed that might add icons?

I didn't installed anything else File Icons package for customizing icons or tabs.

> If you run the apm list command, it should show a list of all your Atom packages.

There are my packages:

> [36mBuilt-in Atom Packages[39m (90)
> ├── atom-dark-syntax@0.28.0
> ├── atom-dark-ui@0.53.0
> ├── atom-light-syntax@0.29.0
> ├── atom-light-ui@0.46.0
> ├── base16-tomorrow-dark-theme@1.5.0
> ├── base16-tomorrow-light-theme@1.5.0
> ├── one-dark-ui@1.10.3
> ├── one-light-ui@1.10.3
> ├── one-dark-syntax@1.7.1
> ├── one-light-syntax@1.7.1
> ├── solarized-dark-syntax@1.1.2
> ├── solarized-light-syntax@1.1.2
> ├── about@1.7.6
> ├── archive-view@0.63.2
> ├── autocomplete-atom-api@0.10.1
> ├── autocomplete-css@0.16.1
> ├── autocomplete-html@0.7.3
> ├── autocomplete-plus@2.35.3
> ├── autocomplete-snippets@1.11.0
> ├── autoflow@0.29.0
> ├── autosave@0.24.2
> ├── background-tips@0.27.0
> ├── bookmarks@0.44.3
> ├── bracket-matcher@0.85.5
> ├── command-palette@0.40.4
> ├── dalek@0.2.1
> ├── deprecation-cop@0.56.7
> ├── dev-live-reload@0.47.1
> ├── encoding-selector@0.23.3
> ├── exception-reporting@0.41.4
> ├── find-and-replace@0.208.3
> ├── fuzzy-finder@1.5.8
> ├── git-diff@1.3.5
> ├── go-to-line@0.32.0
> ├── grammar-selector@0.49.4
> ├── image-view@0.61.2
> ├── incompatible-packages@0.27.3
> ├── keybinding-resolver@0.38.0
> ├── line-ending-selector@0.6.3
> ├── link@0.31.3
> ├── markdown-preview@0.159.12
> ├── metrics@1.2.5
> ├── notifications@0.67.2
> ├── open-on-github@1.2.1
> ├── package-generator@1.1.1
> ├── settings-view@0.249.4
> ├── snippets@1.1.4
> ├── spell-check@0.71.4
> ├── status-bar@1.8.7
> ├── styleguide@0.49.6
> ├── symbols-view@0.115.5
> ├── tabs@0.106.0
> ├── timecop@0.36.0
> ├── tree-view@0.217.1
> ├── update-package-dependencies@0.12.0
> ├── welcome@0.36.3
> ├── whitespace@0.36.2
> ├── wrap-guide@0.40.1
> ├── language-c@0.57.0
> ├── language-clojure@0.22.2
> ├── language-coffee-script@0.48.6
> ├── language-csharp@0.14.2
> ├── language-css@0.42.2
> ├── language-gfm@0.88.1
> ├── language-git@0.19.0
> ├── language-go@0.43.1
> ├── language-html@0.47.2
> ├── language-hyperlink@0.16.1
> ├── language-java@0.27.0
> ├── language-javascript@0.126.1
> ├── language-json@0.19.0
> ├── language-less@0.32.0
> ├── language-make@0.22.3
> ├── language-mustache@0.13.1
> ├── language-objective-c@0.15.1
> ├── language-perl@0.37.0
> ├── language-php@0.38.0
> ├── language-property-list@0.9.1
> ├── language-python@0.45.2
> ├── language-ruby@0.71.0
> ├── language-ruby-on-rails@0.25.2
> ├── language-sass@0.59.0
> ├── language-shellscript@0.25.0
> ├── language-source@0.9.0
> ├── language-sql@0.25.4
> ├── language-text@0.7.2
> ├── language-todo@0.29.1
> ├── language-toml@0.18.1
> ├── language-xml@0.35.0
> └── language-yaml@0.29.0
> 
> [36mCommunity Packages (32)[39m /Users/fatihturan/.atom/packages
> ├── atom-name-that-color@0.2.0
> ├── atom-transpose@0.3.4
> ├── autocomplete-paths@1.0.5
> ├── busy-signal@1.4.3
> ├── comment-commander@0.2.0
> ├── emmet@2.4.3
> ├── git-plus@7.9.3
> ├── gloom@0.6.4
> ├── hey-pane@1.0.0
> ├── intentions@1.1.2
> ├── language-ejs@0.4.0
> ├── language-markdown@0.23.0
> ├── language-typescript-grammars-only@1.6.0
> ├── linter@2.1.4
> ├── linter-csslint@1.3.4
> ├── linter-htmlhint@1.3.3
> ├── linter-jshint@3.1.2
> ├── linter-sass-lint@1.7.4
> ├── linter-scss-lint@3.1.0
> ├── linter-ui-default@1.6.0
> ├── merge-conflicts@1.4.5
> ├── minimap@4.28.2
> ├── minimap-hide@0.3.0
> ├── pigments@0.39.1
> ├── pinned-tabs@1.1.0
> ├── project-plus@1.0.0
> ├── restart-atom@0.2.0
> ├── show-in-system@0.4.0
> ├── split-and-move@0.2.0
> ├── sunset@1.2.0
> ├── sync-settings@0.8.1
> └── toggle-gutter@0.3.3

**Comment by rsese** [comment] 2017-06-09 19:46
Thanks for the package list, it looks like pinned-tabs is the issue.    I can reproduce by installing pinned-tabs and the overlapping icon goes away once I disable it.  If you can confirm, I'd recommend opening an issue in the project's issue tracker: https://github.com/ericcornelissen/pinned-tabs-for-atom. 

For future reference, if things work in safe mode, one approach is to disable all community packages and enable them one-by-one to find the one causing the issue.  But I went ahead and did a quick scan of your community packages to see if anything seemed related to icons or tabs which made me take a look at pinned-tabs.

 I'll go ahead and close this for now but let us know if disabling pinned-tabs doesn't resolve things for you :v:

**Closed by rsese** 2017-06-09 19:46 UTC
Labels: more-information-needed, needs-reproduction

**Comment by simurai** [comment] 2017-06-10 07:26
@rsese Yes, I can reproduce it with `pinned-tabs` too. Thanks for finding the pin in the haystack. :grin:

**Comment by fatihturan** [comment] 2017-06-12 09:31
Thank you guys for your interests. I can [confirm that problem related with `pinned-tabs` package](https://cl.ly/kqSf) and writed a new issue under Pinned Tabs package repo.
